# Generated by Django 3.2.3 on 2021-05-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amounttaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanactno', models.CharField(max_length=50)),
                ('actno', models.CharField(max_length=50)),
                ('loantype', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('amountemi', models.IntegerField(default=0)),
                ('emi', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'loanamtsac',
            },
        ),
        migrations.CreateModel(
            name='Bussinessloan',
            fields=[
                ('email', models.CharField(max_length=100, primary_key='True', serialize=False)),
                ('actno', models.CharField(max_length=100, unique='True')),
                ('loanactno', models.CharField(max_length=100, unique='True')),
                ('loantype', models.CharField(default='', max_length=50)),
                ('interest', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('amounthavetopay', models.IntegerField()),
                ('salary', models.IntegerField(default=0)),
                ('emi', models.IntegerField()),
                ('timeperiod', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('amounttaken', models.IntegerField()),
                ('amountbalance', models.IntegerField()),
                ('amountpayed', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'businessloan',
            },
        ),
        migrations.CreateModel(
            name='Homeloan',
            fields=[
                ('email', models.CharField(max_length=100, primary_key='True', serialize=False)),
                ('actno', models.CharField(max_length=100, unique='True')),
                ('loanactno', models.CharField(max_length=100, unique='True')),
                ('loantype', models.CharField(default='', max_length=50)),
                ('interest', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('amounthavetopay', models.IntegerField()),
                ('salary', models.IntegerField(default=0)),
                ('emi', models.IntegerField()),
                ('timeperiod', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('amounttaken', models.IntegerField()),
                ('amountbalance', models.IntegerField()),
                ('amountpayed', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'homeloan',
            },
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('email', models.CharField(max_length=100, primary_key='True', serialize=False)),
                ('actno', models.CharField(max_length=100)),
                ('loantype', models.CharField(max_length=50)),
                ('interest', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('salary', models.IntegerField(default=0)),
                ('emi', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('timeperiod', models.IntegerField()),
            ],
            options={
                'db_table': 'loans',
            },
        ),
        migrations.CreateModel(
            name='Newuser',
            fields=[
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(max_length=100, primary_key='True', serialize=False)),
                ('panno', models.CharField(max_length=100, unique='True')),
                ('adharno', models.CharField(max_length=100, unique='True')),
                ('dob', models.CharField(max_length=10)),
                ('phnnum', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'newuser',
            },
        ),
        migrations.CreateModel(
            name='Personalloan',
            fields=[
                ('email', models.CharField(max_length=100, primary_key='True', serialize=False)),
                ('actno', models.CharField(max_length=100, unique='True')),
                ('loanactno', models.CharField(max_length=100, unique='True')),
                ('loantype', models.CharField(default='', max_length=50)),
                ('interest', models.IntegerField()),
                ('amounthavetopay', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('salary', models.IntegerField(default=0)),
                ('emi', models.IntegerField()),
                ('timeperiod', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('amounttaken', models.IntegerField()),
                ('amountbalance', models.IntegerField()),
                ('amountpayed', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'personalloan',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('panno', models.CharField(max_length=100, unique='True')),
                ('adharno', models.CharField(max_length=100, unique='True')),
                ('email', models.CharField(max_length=100, primary_key='True', serialize=False)),
                ('actno', models.CharField(max_length=100, unique='True')),
                ('actcif', models.CharField(max_length=100, unique='True')),
                ('actifsc', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('balance', models.IntegerField(default=0)),
                ('branch', models.CharField(max_length=10)),
                ('phnnum', models.CharField(max_length=13)),
                ('city', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('propertyamount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Studyloan',
            fields=[
                ('email', models.CharField(max_length=100, primary_key='True', serialize=False)),
                ('actno', models.CharField(max_length=100, unique='True')),
                ('loanactno', models.CharField(max_length=100, unique='True')),
                ('loantype', models.CharField(default='', max_length=50)),
                ('interest', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('salary', models.IntegerField(default=0)),
                ('emi', models.IntegerField()),
                ('amounthavetopay', models.IntegerField()),
                ('timeperiod', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('amounttaken', models.IntegerField()),
                ('amountbalance', models.IntegerField()),
                ('amountpayed', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'studyloan',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email_Id', models.CharField(max_length=100)),
                ('Account_Number', models.CharField(max_length=50)),
                ('Type_Of_Transaction', models.CharField(max_length=50)),
                ('Date', models.DateTimeField()),
                ('Status', models.CharField(max_length=20)),
                ('Amount', models.IntegerField()),
            ],
            options={
                'db_table': 'transcations',
            },
        ),
        migrations.CreateModel(
            name='Vechileloan',
            fields=[
                ('email', models.CharField(max_length=100, primary_key='True', serialize=False)),
                ('actno', models.CharField(max_length=100, unique='True')),
                ('loanactno', models.CharField(max_length=100, unique='True')),
                ('loantype', models.CharField(default='', max_length=50)),
                ('interest', models.IntegerField()),
                ('amounthavetopay', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('salary', models.IntegerField(default=0)),
                ('emi', models.IntegerField()),
                ('timeperiod', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('amounttaken', models.IntegerField()),
                ('amountbalance', models.IntegerField()),
                ('amountpayed', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'vechileloan',
            },
        ),
    ]
