# Generated by Django 3.2.3 on 2021-05-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bankname', models.CharField(max_length=50)),
                ('loantype', models.CharField(max_length=50)),
                ('intrest', models.IntegerField()),
                ('period', models.IntegerField()),
                ('minsaly', models.IntegerField()),
                ('maxamount', models.IntegerField()),
                ('description', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'banklist',
            },
        ),
    ]
