# Generated by Django 3.2.3 on 2021-05-18 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_banklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banklist',
            name='period',
        ),
    ]
