# Generated by Django 3.2.3 on 2021-05-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_loans_bankname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='interest',
            field=models.IntegerField(default=0),
        ),
    ]
