# Generated by Django 3.2.3 on 2021-05-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_loans_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussinessloan',
            name='bankname',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='homeloan',
            name='bankname',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='personalloan',
            name='bankname',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='studyloan',
            name='bankname',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='vechileloan',
            name='bankname',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
